drm: Fix compilation errors
Errors introduced in commit
d5b4d8ccb1f49b97a643f589efe80b56c3691e69
drm: Add support for platform devices to register as DRM devices

2 simple (merge?) errors:
 - missed ; at drm_pci.c:99
 - parameter 'ent' in drm_fill_in_dev should be 'const'

Signed-off-by: Vladimir Kondratiev <vkondrat@qualcomm.com>