EHCI: msm: Fix compilation error on enabling function framework
Error introduced in commit:
de83ba4641a29e829d13589675467946c72abb9b
msm: release wakelock and pm_qos for max AXI on bus suspend

Error: 'mhcd' undeclared at ehci-msm.c:405

Signed-off-by: Manu Gautam <mgautam@qualcomm.com>